import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { ConfigProvider } from 'antd'
import dayjs from 'dayjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

dayjs.locale('zh-cn')
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>

        <AntdRegistry> <Providers><ConfigProvider> {children} </ConfigProvider> </Providers></AntdRegistry>


      </body>

    </html>
  )
}
